package types

import "time"

// ClientEventV1 represents an event sent from a tracking script to Zori for ingestion.
type ClientEventV1 struct {
	// EventName is a name of the event, it can be nil if the event is not a custom event.
	EventName *string `json:"event_name"`
	// ClientGeneratedEventID just a UUID generated by the client.
	ClientGeneratedEventID string `json:"client_generated_event_id"`
	// VisitorID is a unique identifier for the visitor generated by the client for tracking purposes.
	// This id is created based on the fingerprint of the browser and device.
	VisitorID          string    `json:"visitor_id"`
	ClientTimeStampUTC time.Time `json:"client_timestamp_utc"`
	// UserAgent and IP will be overridden by the server.
	UserAgent string `json:"user_agent"`
	IP        string `json:"ip"`
	// Referrer is the URL of the page that linked to the current page.
	// Used to determine the source of traffic
	Referrer string `json:"referrer"`
	PageURL  string `json:"page_url"`
	// ClickOn represents the element that was clicked on.
	// ClickOn is used to help us build custom funnels and goals for user conversion.
	ClickOn *string `json:"click_on"`
	// ClickPosition represents the position of the click on the element.
	// ClickPosition is used to track the exact location of the click within the element in order to build heatmaps and analyze user behavior.
	ClickPosition    *[]float64        `json:"click_position"`
	UTMParameters    map[string]string `json:"utm_parameters"`
	CustomProperties map[string]any    `json:"custom_properties"`
}
