package types

import "time"

// ClickElement represents detailed information about a clicked element
type ClickElement struct {
	Tag      string `json:"tag"`      // HTML tag name (e.g., "button", "a", "div")
	Selector string `json:"selector"` // CSS selector (e.g., "#submit-btn", ".cta-button")
	Text     string `json:"text"`     // Text content of the element
}

// ClickPosition represents the exact position of a click event
type ClickPosition struct {
	X            float64 `json:"x"`             // X coordinate of the click
	Y            float64 `json:"y"`             // Y coordinate of the click
	ScreenWidth  uint16  `json:"screen_width"`  // Browser viewport width
	ScreenHeight uint16  `json:"screen_height"` // Browser viewport height
}

// ClientEventV1 represents an event sent from a tracking script to Zori for ingestion.
type ClientEventV1 struct {
	// EventName is a name of the event, it can be nil if the event is not a custom event.
	EventName *string `json:"event_name"`
	// ClientGeneratedEventID just a UUID generated by the client.
	ClientGeneratedEventID string `json:"client_generated_event_id"`
	// VisitorID is a unique identifier for the visitor generated by the client for tracking purposes.
	// This id is created based on the fingerprint of the browser and device.
	VisitorID string `json:"visitor_id"`
	// SessionID is a unique identifier for the current session generated by the client.
	// Used to group events within a single user session for session-based analytics.
	SessionID          string    `json:"session_id"`
	ClientTimeStampUTC time.Time `json:"client_timestamp_utc"`
	// UserAgent and IP will be overridden by the server.
	UserAgent string `json:"user_agent"`
	IP        string `json:"ip"`
	// Referrer is the URL of the page that linked to the current page.
	// Used to determine the source of traffic (can be null)
	Referrer *string `json:"referrer"`
	// PageURL is the path of the current page (e.g., "/", "/about")
	PageURL string `json:"page_url"`
	// Host is the domain name (e.g., "mention.click", "example.com")
	Host string `json:"host"`
	// ClickElement contains detailed information about the clicked element
	// Used to build custom funnels and goals for user conversion
	ClickElement *ClickElement `json:"click_element"`
	// ClickPosition represents the exact position of the click within the viewport
	// Used to build heatmaps and analyze user behavior
	ClickPosition    *ClickPosition    `json:"click_position"`
	UTMParameters    map[string]string `json:"utm_parameters"`
	CustomProperties map[string]any    `json:"custom_properties"`
}
