version: "3"
includes:
  lib:
    taskfile: ./tasks/Taskfile.tests.yaml
    flatten: true

dotenv: [".env"]

vars:
  GO_MODULE: zori

tasks:
  server:
    aliases:
      - s
    desc: Start the API HTTP server (default port 1323)
    cmds:
      - go run . server {{.CLI_ARGS}}

  ingestion:
    aliases:
      - i
    desc: Start the Ingestion HTTP server (default port 1324)
    cmds:
      - go run . ingestion {{.CLI_ARGS}}

  migrate:up:
    desc: Run all pending database migrations
    cmds:
      - goose -dir internal/storage/postgres/migrations postgres "$POSTGRES_URL" up
      - GOOSE_DRIVER=clickhouse GOOSE_DBSTRING="clickhouse://$CLICKHOUSE_USERNAME:$CLICKHOUSE_PASSWORD@$CLICKHOUSE_URL" goose -dir internal/storage/clickhouse/migrations up

  migrate:down:
    desc: Rollback the last database migration
    cmds:
      - goose -dir internal/storage/postgres/migrations postgres "$POSTGRES_URL" down
      - GOOSE_DRIVER=clickhouse GOOSE_DBSTRING=$CLICKHOUSE_URL goose -dir internal/storage/clickhouse/migrations down

  docs:
    desc: Generate Swagger documentation
    cmds:
      - npm install -g api-spec-converter
      - swag init -g main.go --parseDependency --parseInternal --parseDepth 2 --parseFuncBody
      - npx api-spec-converter --syntax=json --from=swagger_2 --to=openapi_3 docs/swagger.json > docs/openapi.json
      - npx api-spec-converter --syntax=yaml --from=swagger_2 --to=openapi_3 docs/swagger.yaml > docs/openapi.yaml
      - rm docs/swagger.yaml
      - rm docs/swagger.json
    silent: true

  start:
    desc: Quick start - setup environment and run server
    cmds:
      - task: migrate:up
      - task: server
