version: "3"
includes:
  tests:
    taskfile: ./tasks/Taskfile.tests.yaml
    flatten: true
  docs:
    taskfile: ./tasks/Taskfile.docs.yaml
    flatten: true
  resources:
    taskfile: ./tasks/Taskfile.resources.yaml
    flatten: true

dotenv: [".env"]

vars:
  GO_MODULE: zori

tasks:
  server:
    aliases:
      - s
    desc: Start the API HTTP server (default port 1323)
    deps:
      - pullipdb
    cmds:
      - go run . server {{.CLI_ARGS}}

  ingestion:
    aliases:
      - i
    desc: Start the Ingestion HTTP server (default port 1324)
    deps:
      - pullipdb
    cmds:
      - go run . ingestion {{.CLI_ARGS}}

  migrate:up:
    desc: Run all pending database migrations
    cmds:
      - goose -dir internal/storage/postgres/migrations postgres "$POSTGRES_URL" up
      - GOOSE_DRIVER=clickhouse GOOSE_DBSTRING="clickhouse://$CLICKHOUSE_USERNAME:$CLICKHOUSE_PASSWORD@$CLICKHOUSE_URL" goose -dir internal/storage/clickhouse/migrations up

  migrate:down:
    desc: Rollback the last database migration
    cmds:
      - goose -dir internal/storage/postgres/migrations postgres "$POSTGRES_URL" down
      - GOOSE_DRIVER=clickhouse GOOSE_DBSTRING=$CLICKHOUSE_URL goose -dir internal/storage/clickhouse/migrations down

  start:
    desc: Quick start - setup environment and run server
    cmds:
      - task: migrate:up
      - task: server
