version: "3"

vars:
  GO_MODULE: zori

tasks:
  docs:
    desc: Generate Swagger documentation
    cmds:
      - npm install -g api-spec-converter
      - swag init -g main.go --parseDependency --parseInternal --parseDepth 2 --parseFuncBody
      - npx api-spec-converter --syntax=json --from=swagger_2 --to=openapi_3 docs/swagger.json > docs/openapi.json
      - npx api-spec-converter --syntax=yaml --from=swagger_2 --to=openapi_3 docs/swagger.yaml > docs/openapi.yaml
      - rm docs/swagger.yaml
      - rm docs/swagger.json
    silent: true
